In [1]:
import pandas as pd
from collections import defaultdict

In [2]:

city_classification = {
    "一线城市": ["北京", "上海", "广州", "深圳"],
    "新一线城市": ["成都", "重庆", "杭州", "武汉", "西安", "天津", "苏州", "南京", "郑州", "长沙", "东莞", "沈阳", "青岛", "合肥", "佛山"],
    "二线城市": ["宁波", "昆明", "福州", "无锡", "厦门", "济南", "大连", "温州", "泉州", "南宁", "南昌", "石家庄", "金华", "常州", "惠州", "嘉兴", "南通", "徐州", "绍兴", "台州", "太原", "珠海", "中山", "保定", "兰州", "哈尔滨", "长春", "贵阳", "烟台", "廊坊"],
    "三线城市": ["潍坊", "海口", "扬州", "汕头", "洛阳", "乌鲁木齐", "临沂", "唐山", "镇江", "盐城", "湖州", "赣州", "济宁", "泰州", "呼和浩特", "咸阳", "芜湖", "三亚", "漳州", "揭阳", "江门", "桂林", "邯郸", "银川", "阜阳", "淮安", "衡阳", "遵义", "柳州", "淄博", "湛江", "上饶", "莆田", "绵阳", "商丘", "九江", "新乡", "信阳", "宜昌", "沧州", "连云港", "南阳", "岳阳", "襄阳", "蚌埠", "宁德", "邢台", "株洲", "周口", "马鞍山", "清远", "驻马店", "潮州", "滁州", "威海", "宿迁", "秦皇岛", "肇庆", "荆州", "宿州", "菏泽", "鞍山", "安庆", "黄冈", "泰安", "南充", "六安", "宜春", "大庆", "舟山"],
    "四线城市": ["孝感", "丽水", "运城", "德州", "许昌", "常德", "渭南", "晋中", "安阳", "三明", "开封", "郴州", "茂名", "湘潭", "营口", "邵阳", "德阳", "龙岩", "淮南", "黄石", "南平", "韶关", "亳州", "日照", "西宁", "衢州", "东营", "吉林", "梅州", "聊城", "枣庄", "包头", "怀化", "宣城", "临汾", "盘锦", "锦州", "榆林", "抚州", "景德镇", "北海", "宝鸡", "焦作", "平顶山", "玉林", "十堰", "汕尾", "咸宁", "宜宾", "滨州", "永州", "吉安", "益阳", "黔南", "丹东", "曲靖", "乐山", "鄂尔多斯", "阳江", "泸州", "黄山", "黔东南", "张家口", "大理", "大同", "恩施", "衡水", "铜陵", "承德", "红河", "河源", "延边", "齐齐哈尔", "延安", "漯河", "葫芦岛", "娄底", "抚顺", "拉萨", "铜仁", "长治", "达州", "忻州", "鄂州", "淮北", "濮阳", "眉山", "池州", "荆门", "吕梁"],
    "五线城市": ["汉中", "辽阳", "梧州", "鹰潭", "百色", "毕节", "钦州", "云浮", "佳木斯", "朝阳", "贵港", "四平", "丽江", "内江","安顺", "三门峡", "赤峰", "六盘水", "新余", "牡丹江", "晋城", "自贡", "本溪", "防城港", "铁岭", "随州", "广安", "广元", "天水", "遂宁", "萍乡", "西双版纳", "绥化", "鹤壁", "湘西","张家界", "松原", "阜新", "酒泉", "黔西南", "保山", "昭通","贺州", "通化", "克拉玛依", "呼伦贝尔", "阳泉", "河池", "来宾", "通辽", "玉溪", "安康", "德宏", "楚雄", "朔州", "伊犁", "文山", "嘉峪关", "凉山", "资阳", "雅安", "锡林郭勒", "普洱","崇左", "庆阳",  "巴音郭楞", "乌兰察布", "白山","昌吉", "白城","兴安", "定西", "喀什", "白银", "陇南", "张掖", "商洛", "哈密", "黑河", "吴忠", "攀枝花", "巴彦淖尔", "巴中", "鸡西","乌海", "临沧", "海东", "双鸭山", "阿克苏", "石嘴山", "阿拉善","辽源", "临夏", "铜川", "海西", "平凉", "金昌", "鹤岗","林芝", "伊春", "固原", "武威", "儋州", "甘孜", "吐鲁番","怒江", "和田", "迪庆", "甘南", "阿坝", "大兴安岭", "中卫","塔城", "博尔塔拉", "昌都", "阿勒泰", "七台河", "山南", "日喀则", "玉树", "海南", "果洛", "克孜勒苏", "阿里", "海北", "黄南", "那曲","三沙"]

}


city_list = []
for level, cities in city_classification.items():
    for city in cities:
        city_list.append({"rev_addr_city_id": city, "city_level": level})


city_df = pd.DataFrame(city_list)

In [3]:
data_all = pd.read_csv('filter_data_2.csv')

data_all = data_all.groupby(['rev_addr_city_id','item_first_cate_name', 'year'])['nums'].sum().reset_index()
data_all = data_all.reset_index(drop=True)

In [4]:
test_nan_gdp = data_all[data_all['nums'].isna()]
test_nan_gdp

Empty DataFrame
Columns: [rev_addr_city_id, item_first_cate_name, year, nums]
Index: []

In [5]:
df = pd.DataFrame(data_all)

pivot_df = df.pivot(index=['rev_addr_city_id', 'year'], columns='item_first_cate_name', values='nums').reset_index()
pivot_df = pivot_df.fillna(0).reset_index(drop=True)

In [6]:
df1 = pd.DataFrame(pivot_df)


unique_cities = pd.unique(df1['rev_addr_city_id'])
char_dict = defaultdict(list)
for city in unique_cities:
    char_dict[city[:2]].append(city)


duplicates = {key: value for key, value in char_dict.items() if len(value) > 1}


if duplicates:

    cities_with_duplicates = [city for cities in duplicates.values() for city in cities]
    has_duplicates = df1[df1['rev_addr_city_id'].isin(cities_with_duplicates)]
    no_duplicates = df1[~df1['rev_addr_city_id'].isin(cities_with_duplicates)]
else:

    has_duplicates = pd.DataFrame(columns=df1.columns)
    no_duplicates = df1.copy()

In [7]:
df1 = no_duplicates.copy()
df2 = city_df.copy()

df1['city_prefix'] = df1['rev_addr_city_id'].str[:2]
df2['city_prefix'] = df2['rev_addr_city_id'].str[:2]

In [8]:

merged_df = pd.merge(df1, df2, on=['city_prefix'], how='left')

merged_df = merged_df.drop(columns=['city_prefix','rev_addr_city_id_y'])
merged_df.rename(columns={'rev_addr_city_id_x': 'rev_addr_city_id'}, inplace=True)
merged_df['city_level'] = merged_df['city_level'].fillna('六线城市')
merged_1 = merged_df.copy()
no_duplicates = merged_1.copy()

In [9]:
df1 = has_duplicates.copy()
df2 = city_df.copy()

df1['city_prefix'] = df1['rev_addr_city_id'].str[:3]
df2['city_prefix'] = df2['rev_addr_city_id'].str[:3]

In [10]:

merged_df = pd.merge(df1, df2, on=['city_prefix'], how='left')

merged_df = merged_df.drop(columns=['city_prefix','rev_addr_city_id_y'])
merged_df.rename(columns={'rev_addr_city_id_x': 'rev_addr_city_id'}, inplace=True)
merged_df['city_level'] = merged_df['city_level'].fillna('六线城市')
merged_2 = merged_df.copy()
has_duplicates = merged_2.copy()

In [11]:
final_merged_df = pd.concat([merged_1, merged_2], ignore_index=True)

In [12]:
gdp=pd.read_csv('GDP-all.csv')
gdp = gdp[['rev_addr_city_id','year','gdp']]

In [13]:
people=pd.read_csv('people-all.csv')
people.rename(columns={'常住人口': 'people'}, inplace=True)
people = people[['rev_addr_city_id','year','people']]

In [14]:
df1 = final_merged_df.copy()
df2 = people.copy()
df3 = gdp.copy()
merged_df_1 = pd.merge(df1, df2, on=['rev_addr_city_id','year'], how='left')
merged_df_all = pd.merge(merged_df_1, df3, on=['rev_addr_city_id','year'], how='left')

In [15]:
test_nan_gdp = merged_df_all[(merged_df_all['people'].isna()) | (merged_df_all['gdp'].isna())]

In [16]:
cities_to_exclude = test_nan_gdp['rev_addr_city_id'].unique()
final_merged_df = merged_df_all[~merged_df_all['rev_addr_city_id'].isin(cities_to_exclude)]

In [17]:
filter_number = data_all[~data_all['rev_addr_city_id'].isin(cities_to_exclude)]

In [18]:
filter_number_grouped_df = filter_number.groupby(['item_first_cate_name', 'year'])['nums'].sum().reset_index()

In [19]:
filter_number_grouped_df_2021 = filter_number_grouped_df[filter_number_grouped_df['year'] == 2021]
filter_number_grouped_df_2021 = filter_number_grouped_df_2021[['item_first_cate_name','nums']]

In [20]:
filter_number_grouped_df_2022 = filter_number_grouped_df[filter_number_grouped_df['year'] == 2022]
filter_number_grouped_df_2022 = filter_number_grouped_df_2022[['item_first_cate_name','nums']]

In [21]:
df = pd.DataFrame(final_merged_df)
df = df[df['year'] == 2022]
# Group by 'rev_addr_city_id' and count the occurrences of each city
city_counts = df['city_level'].value_counts()

In [22]:
df = pd.DataFrame(final_merged_df)

# Group by 'rev_addr_city_id' and count the occurrences of each city
city_counts = df['rev_addr_city_id'].value_counts()

# Find cities where the count is greater than 3
cities_greater_than_3 = city_counts[city_counts > 2].index.tolist()

cities_greater_than_3

[]

In [23]:
df = pd.DataFrame(final_merged_df)

# Group by 'rev_addr_city_id' and count the occurrences of each city
city_counts = df['rev_addr_city_id'].value_counts()

# Find cities where the count is greater than 3
cities_greater_than_3 = city_counts[city_counts < 1].index.tolist()

cities_greater_than_3

[]

In [24]:
final_merged_df['city_level'] = final_merged_df['city_level'].replace(['一线城市', '新一线城市'], '一新一')

/tmp/ipykernel_32413/1035597093.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_merged_df['city_level'] = final_merged_df['city_level'].replace(['一线城市', '新一线城市'], '一新一')

# Divide the experimental set

In [25]:
data_exp_1 = final_merged_df.dropna()

target_column = 'city_level'
columns = [col for col in data_exp_1.columns if col != target_column]
columns.insert(2, target_column)

data_exp_1 = data_exp_1[columns]
data_exp_1 = data_exp_1.reset_index(drop=True)

In [26]:
data_exp_2 = data_exp_1.dropna()

data_exp_2['Sum'] = data_exp_2.iloc[:, 3:-2].sum(axis=1)

data_exp_2 = data_exp_2[['rev_addr_city_id','year','city_level', 'Sum','people','gdp']]
data_exp_2 = data_exp_2.reset_index(drop=True)

In [27]:
data_exp_3 = data_exp_1.dropna()
data_exp_3 = data_exp_3.drop(columns=['people'])
data_exp_3 = data_exp_3.reset_index(drop=True)

In [28]:
data_exp_4 = data_exp_2.dropna()
data_exp_4 = data_exp_4.drop(columns=['people'])
data_exp_4 = data_exp_4.reset_index(drop=True)

In [29]:
data_exp_5 = final_merged_df.dropna()

target_column = 'city_level'
columns = [col for col in data_exp_5.columns if col != target_column]
columns.insert(2, target_column)

data_exp_5 = data_exp_5[columns]

data_exp_5 = data_exp_5[['rev_addr_city_id','year','city_level','people','gdp']]

data_exp_5 = data_exp_5.reset_index(drop=True)

In [30]:
import numpy as np
import pandas as pd
import xgboost as xgb
from itertools import product
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import ElasticNet, LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, make_scorer
from sklearn.model_selection import (train_test_split, KFold, GroupKFold, StratifiedKFold,
                                     StratifiedShuffleSplit, GridSearchCV)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from tqdm import tqdm
import warnings


warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb
from itertools import product
from tqdm import tqdm 
import warnings
from sklearn.exceptions import ConvergenceWarning
from tqdm import tqdm


def mean_absolute_percentage_error(y_true, y_pred): 
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

def EN_CV(X_train, y_train, param_grid, stratifier):
    best_r2_test = -np.inf
    best_params = None
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    pbar = tqdm(total=skf.get_n_splits() * len(param_grid['alpha']) * len(param_grid['l1_ratio']))

    for train_index, test_index in skf.split(X_train, stratifier):
        X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
        y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]

        scaler_X = StandardScaler()
        X_train_scaled = scaler_X.fit_transform(X_train_fold)
        X_test_scaled = scaler_X.transform(X_test_fold)
        
        scaler_y = StandardScaler()
        y_train_scaled = scaler_y.fit_transform(y_train_fold.reshape(-1, 1)).ravel()
        y_test_scaled = scaler_y.transform(y_test_fold.reshape(-1, 1)).ravel()
        
        for alpha in param_grid['alpha']:
            for l1_ratio in param_grid['l1_ratio']:
                model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, max_iter=10000)
                model.fit(X_train_scaled, y_train_scaled)
                y_test_pred_scaled = model.predict(X_test_scaled)
                y_test_pred = scaler_y.inverse_transform(y_test_pred_scaled.reshape(-1, 1)).ravel()
                r2_test = r2_score(y_test_fold, y_test_pred)

                if r2_test > best_r2_test:
                    best_r2_test = r2_test
                    best_params = {'alpha': alpha, 'l1_ratio': l1_ratio}

                pbar.update(1)

    pbar.close()
    return best_r2_test, best_params

In [32]:
from sklearn.model_selection import KFold
import numpy as np
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn.preprocessing import StandardScaler


def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    

def EN_evaluate(data, model_name, param_grid, year):
    data = data[data['year'] == year]
    data = data.reset_index(drop=True)
    feature_names = data.columns[3:-1]
    X = data.iloc[:, 3:-1].values
    y = data.iloc[:, -1].values

    stratifier = data['city_level']

    metrics_list = []
    best_r2_test = -np.inf
    best_weights = None
    best_params = None

    X_train, X_test, y_train, y_test, strat_train, strat_test = train_test_split(X, y, stratifier, test_size=0.3, stratify=stratifier, random_state=51)

    r2_cv, current_best_params = EN_CV(X_train, y_train, param_grid, strat_train)

    scaler_X = StandardScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_test_scaled = scaler_X.transform(X_test)

    scaler_y = StandardScaler()
    y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()
    y_test_scaled = scaler_y.transform(y_test.reshape(-1, 1)).ravel()

    xg_reg = ElasticNet(
        alpha=current_best_params['alpha'],
        l1_ratio=current_best_params['l1_ratio'],
        max_iter=10000
    )
    xg_reg.fit(X_train_scaled, y_train_scaled)

    y_train_pred_scaled = xg_reg.predict(X_train_scaled)
    y_test_pred_scaled = xg_reg.predict(X_test_scaled)

    y_train_pred = scaler_y.inverse_transform(y_train_pred_scaled.reshape(-1, 1)).ravel()
    y_test_pred = scaler_y.inverse_transform(y_test_pred_scaled.reshape(-1, 1)).ravel()

    r2_test = r2_score(y_test, y_test_pred)

    best_weights = xg_reg.coef_
    best_params = current_best_params

    fold_metrics = {
        'RMSE_train': np.sqrt(mean_squared_error(y_train, y_train_pred)),
        'MAPE_train': mean_absolute_percentage_error(y_train, y_train_pred),
        'MAE_train': mean_absolute_error(y_train, y_train_pred),
        'R2_train': r2_score(y_train, y_train_pred),
        'RMSE_test': np.sqrt(mean_squared_error(y_test, y_test_pred)),
        'MAPE_test': mean_absolute_percentage_error(y_test, y_test_pred),
        'MAE_test': mean_absolute_error(y_test, y_test_pred),
        'R2_test': r2_test
    }

    metrics_list.append({**fold_metrics})

    results_df = pd.DataFrame(metrics_list)
    results_df.insert(0, 'Data', model_name)

    best_weights_df = pd.DataFrame({'Feature': feature_names, 'Weight': best_weights})

    return best_weights_df, results_df, best_params

In [33]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


warnings.filterwarnings("ignore", category=UserWarning)


EN_param_grid = {
    'alpha': [0.00,0.01,0.1,1.0, 5.0, 10], # , 5.0, 10.0, 20.0, 50.0, 100, 200
    'l1_ratio': np.arange(0, 1.01, 0.01)
}

dataframes = {
    'data_exp_1': data_exp_1,
    'data_exp_2': data_exp_2,
    'data_exp_3': data_exp_3,
    'data_exp_4': data_exp_4,
    'data_exp_5': data_exp_5
}

years = [2021, 2022]

EN_results = pd.DataFrame()
EN_weights = pd.DataFrame()
EN_param = pd.DataFrame()

for name, df in dataframes.items():
    for year in years:
        average_weights, result_df, best_params = EN_evaluate(df, name, EN_param_grid, year)
        
        result_df['Data'] = f"{name}_{year}"
        EN_results = pd.concat([EN_results, result_df], ignore_index=True)

        average_weights['Experiment'] = f"{name}_{year}"
        EN_weights = pd.concat([EN_weights, average_weights], ignore_index=True)

        best_params_df = pd.DataFrame([best_params])
        best_params_df['Experiment'] = f"{name}_{year}"
        EN_param = pd.concat([EN_param, best_params_df], ignore_index=True)

100%|██████████| 3030/3030 [00:55<00:00, 54.25it/s]
100%|██████████| 3030/3030 [00:56<00:00, 53.58it/s]
100%|██████████| 3030/3030 [00:08<00:00, 348.14it/s]
100%|██████████| 3030/3030 [00:08<00:00, 355.33it/s]
100%|██████████| 3030/3030 [01:09<00:00, 43.42it/s]
100%|██████████| 3030/3030 [01:07<00:00, 45.00it/s]
100%|██████████| 3030/3030 [00:07<00:00, 418.97it/s]
100%|██████████| 3030/3030 [00:07<00:00, 431.64it/s]
100%|██████████| 3030/3030 [00:07<00:00, 408.10it/s]
100%|██████████| 3030/3030 [00:07<00:00, 426.40it/s]

In [34]:
all_results_2021 = EN_results[EN_results['Data'].str.contains('2021')]
all_results_2022 = EN_results[EN_results['Data'].str.contains('2022')]

In [35]:
def merge_and_sort_dataframes(df1, df2, ascending=False):
    df1.rename(columns={'Feature': 'item_first_cate_name'}, inplace=True)

    merged_df = pd.merge(df1[['item_first_cate_name', 'Weight']],
                         df2[['item_first_cate_name', 'nums']],
                         on='item_first_cate_name', how='outer')
    
    merged_df['Weight_abs'] = merged_df['Weight'].abs() 
    sorted_merged_df = merged_df.sort_values(by='Weight_abs', ascending=ascending)
    
    sorted_merged_df['Weight_Rank'] = sorted_merged_df['Weight'].abs().rank(ascending=ascending, method='average') 
    sorted_merged_df['Nums_Rank'] = sorted_merged_df['nums'].rank(ascending=False, method='average')  

    return sorted_merged_df

In [36]:
def process_weights_data(EN_weights, year, experiment_name, grouped_df):

    filtered_weights = EN_weights[EN_weights['Experiment'].str.contains(year)]
    filtered_weights = filtered_weights[filtered_weights['Experiment'].str.contains(experiment_name)]
    

    merged_data = merge_and_sort_dataframes(filtered_weights, grouped_df)

    result_df = merged_data[['item_first_cate_name', 'Weight', 'Weight_Rank', 'nums', 'Nums_Rank']]
    
    result_df.loc[:, 'nums'] = result_df['nums'].round(1)

    return result_df

In [37]:
year = "2021"
experiment_name = "data_exp_2"
exp2_EN_weights_2021 = process_weights_data(EN_weights, year, experiment_name, filter_number_grouped_df_2021)

In [38]:
year = "2022"
experiment_name = "data_exp_2"
exp2_EN_weights_2022 = process_weights_data(EN_weights, year, experiment_name, filter_number_grouped_df_2022)

In [39]:
exp2_EN_weights_2021

   item_first_cate_name    Weight  Weight_Rank         nums  Nums_Rank
0                   Sum  0.560941          1.0          NaN        NaN
1                people  0.457082          2.0          NaN        NaN
2                  个人护理       NaN          NaN  546389090.0        2.0
3                  二手商品       NaN          NaN    8923448.0       31.0
4                  京东服务       NaN          NaN    1601268.0       35.0
5                  休闲零食       NaN          NaN   10389694.0       30.0
6                  农资园艺       NaN          NaN   25181108.0       26.0
7                  冲调保健       NaN          NaN    1125470.0       37.0
8                  医疗保健       NaN          NaN  261297511.0        8.0
9                    医药       NaN          NaN  108873996.0       17.0
10                   厨具       NaN          NaN  173311035.0       13.0
11                   图书       NaN          NaN  143296824.0       14.0
12                 宠物生活       NaN          NaN   65366504.0       21.0
13                   家具       NaN          NaN   44373418.0       24.0
14                 家居日用       NaN          NaN  179003414.0       12.0
15              家庭清洁/纸品       NaN          NaN  379098337.0        3.0
16                 家用电器       NaN          NaN  306134287.0        6.0
17                   家纺       NaN          NaN   77817662.0       19.0
18                 家装建材       NaN          NaN  123171068.0       16.0
19                  工业品       NaN          NaN   12781656.0       29.0
20                 手机通讯       NaN          NaN  212276199.0       10.0
21                   数码       NaN          NaN  127851395.0       15.0
22                   文娱       NaN          NaN    1300411.0       36.0
23                 方便速食       NaN          NaN    3592864.0       33.0
24                 服饰内衣       NaN          NaN  355169651.0        4.0
25            本地生活/旅游出行       NaN          NaN     566507.0       39.0
26                   母婴       NaN          NaN  302948433.0        7.0
27                 水饮乳品       NaN          NaN    5194432.0       32.0
28                 汽车用品       NaN          NaN   97340241.0       18.0
29                 玩具乐器       NaN          NaN   71909441.0       20.0
30                 珠宝首饰       NaN          NaN   25083289.0       27.0
31                   生鲜       NaN          NaN  226191754.0        9.0
32                电脑、办公       NaN          NaN  318907053.0        5.0
33                   礼品       NaN          NaN   47971981.0       23.0
34                 箱包皮具       NaN          NaN   37181949.0       25.0
35                 粮油调味       NaN          NaN    1966122.0       34.0
36                 计生用品       NaN          NaN     512027.0       40.0
37                 运动户外       NaN          NaN  183748885.0       11.0
38                   邮币       NaN          NaN     623875.0       38.0
39                   酒类       NaN          NaN   60621662.0       22.0
40                 钟表眼镜       NaN          NaN   13829219.0       28.0
41                 食品饮料       NaN          NaN  885306102.0        1.0

In [40]:
exp2_EN_weights_2022

   item_first_cate_name    Weight  Weight_Rank         nums  Nums_Rank
0                   Sum  0.329430          1.0          NaN        NaN
1                people  0.315044          2.0          NaN        NaN
2                  个人护理       NaN          NaN  549684517.0        2.0
3                  二手商品       NaN          NaN    8944542.0       29.0
4                  京东服务       NaN          NaN    8754887.0       30.0
5                  休闲零食       NaN          NaN    8519368.0       31.0
6                  农资园艺       NaN          NaN   21865901.0       26.0
7                  冲调保健       NaN          NaN    1009488.0       38.0
8                  医疗保健       NaN          NaN  377744469.0        4.0
9                    医药       NaN          NaN  181892914.0       12.0
10                   厨具       NaN          NaN  179532167.0       13.0
11                   图书       NaN          NaN  141414694.0       15.0
12                 宠物生活       NaN          NaN   79858879.0       20.0
13                   家具       NaN          NaN   47221714.0       23.0
14                 家居日用       NaN          NaN  157466077.0       14.0
15              家庭清洁/纸品       NaN          NaN  475894200.0        3.0
16                 家用电器       NaN          NaN  322503767.0        8.0
17                   家纺       NaN          NaN   82874691.0       19.0
18                 家装建材       NaN          NaN  133040046.0       16.0
19                  工业品       NaN          NaN   17922063.0       27.0
20                 手机通讯       NaN          NaN  195694121.0       11.0
21                   数码       NaN          NaN  132409386.0       17.0
22                   文娱       NaN          NaN    1186780.0       37.0
23                 方便速食       NaN          NaN    3237082.0       34.0
24                 服饰内衣       NaN          NaN  326787490.0        6.0
25            本地生活/旅游出行       NaN          NaN    1485004.0       36.0
26                   母婴       NaN          NaN  323634019.0        7.0
27                 水饮乳品       NaN          NaN    3413486.0       33.0
28                 汽车用品       NaN          NaN   94197458.0       18.0
29                 玩具乐器       NaN          NaN   70267327.0       21.0
30                 珠宝首饰       NaN          NaN   28986117.0       25.0
31                   生鲜       NaN          NaN  219981799.0        9.0
32                电脑、办公       NaN          NaN  332337339.0        5.0
33                   礼品       NaN          NaN    8412719.0       32.0
34                 箱包皮具       NaN          NaN   32571795.0       24.0
35                 粮油调味       NaN          NaN    1701533.0       35.0
36                 计生用品       NaN          NaN     527018.0       40.0
37                 运动户外       NaN          NaN  195897920.0       10.0
38                   邮币       NaN          NaN     617428.0       39.0
39                   酒类       NaN          NaN   63829575.0       22.0
40                 钟表眼镜       NaN          NaN   17694369.0       28.0
41                 食品饮料       NaN          NaN  914430896.0        1.0